services:
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./sites:/etc/nginx/conf.d
            - ./html:/var/www/html
            - ./error/nginx:/var/log/nginx
        networks:
            - lnmp
        depends_on:
            - php
        expose:
            - "8000"
        ports:
            - "8000:80"
    php:
        image: php:8.4-fpm
        container_name: php
        volumes:
            - ./html:/var/www/html
        networks:
            - lnmp
        build:
            dockerfile: ./php.Dockerfile
        depends_on:
            - mariadb
            - redis
           # - memcached
        expose:
            - "9000"
    mariadb:
        image: mariadb
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kouhosei
        volumes:
            - ./data/mariadb:/var/lib/mysql
        networks:
            - lnmp
        expose:
            - "3306"
        ports:
            - "3306:3306"
    redis:
        image: redis
        container_name: redis
        volumes:
            - ./data/redis:/data
            - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
        build:
            dockerfile: ./redis.Dockerfile
        networks:
            - lnmp
        expose:
            - "6379"
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 5
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        networks:
            - lnmp
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        networks:
            - lnmp
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
    # memcached:
    #     image: memcached
    #     networks:
    #         - lnmp
    #     expose:
    #         - "11211"

networks:
    lnmp: